import type { LearningDesign } from '../types/schema';

export const CAMPAIGN_MISSION_IDS = [
  'm1-first-lights',
  'm2-wrong-port',
  'm5-change-window',
  'm6-fiber-first',
  'm7-wrong-media',
  'm9-power-up',
  'm4-admin-down',
  'm23-no-shutdown',
  'm28-fiber-no-shutdown',
  'm10-console-ip',
  'm11-subnet-ping',
  'm19-broken-address',
  'm20-mask-trap',
  'm29-spare-pdu',
  'm12-firewall-acl',
  'm18-deny-host',
  'm13-access-vlan',
  'm3-vlan-trap',
  'm14-vlan-isolation',
  'm8-dual-servers',
  'm15-default-gateway',
  'm24-wrong-gateway',
  'm16-trunk-uplink',
  'm21-inter-vlan',
  'm17-static-nat',
  'm31-pat-overload',
  'm22-static-route',
  'm25-host-route',
  'm30-floating-static',
  'm26-deny-branch',
  'm27-branch-exception',
  'm32-traceroute',
] as const;

export type CampaignMissionId = (typeof CAMPAIGN_MISSION_IDS)[number];

export const LEARNING_DESIGN_BY_ID = {
  'm1-first-lights': {
    mode: 'guided',
    difficulty: 1,
    conceptsIntroduced: ['Physical endpoints and link-state evidence'],
    conceptsPracticed: [],
    deviceUnlocks: ['Patch panel', 'ToR switch', 'Copper server', 'Cat6 patch cord'],
    enabledTools: ['patch'],
    visibleObjectives: ['Connect the documented panel circuit to the switch.', 'Bring SERVER-01 online and confirm link lights at both ends.'],
    ticketDetails: ['Use Cat6 between A-01 and Gi1/0/1.', 'Connect SERVER-01 eth0 to Gi1/0/5.'],
    debrief: {
      outcome: 'SERVER-01 has a complete, lit copper path through the top-of-rack switch.',
      explanation: 'A link comes up only when compatible ports are joined at both ends; the LEDs provide immediate physical-layer evidence.',
      question: 'What should you verify before investigating IP settings on a new server connection?',
      answer: 'Verify the intended endpoints, compatible media, and link lights first.',
    },
    hints: {
      prompt: 'Trace the intended circuit from the patch-panel label to the server NIC.',
      evidence: 'A-01, Gi1/0/1, Gi1/0/5, and SERVER-01 eth0 are the documented endpoints.',
      action: 'Patch the panel side and server side with Cat6, then inspect the LEDs.',
      solution: 'Connect A-01 to Gi1/0/1 and Gi1/0/5 to SERVER-01 eth0.',
    },
  },
  'm2-wrong-port': {
    mode: 'practice',
    difficulty: 1,
    conceptsIntroduced: ['Cable removal and clean final state'],
    conceptsPracticed: ['Physical endpoints and link-state evidence'],
    enabledTools: ['patch'],
    visibleObjectives: ['Correct the mislabeled cross-connect.', 'Leave the retired panel port clear while preserving server service.'],
    ticketDetails: ['The ticket calls for panel A-01; A-03 is currently occupied.'],
    debrief: {
      outcome: 'The server remains connected through the documented A-01 circuit and A-03 is clear.',
      explanation: 'A link can be electrically valid but operationally wrong; labels and a clean final rack make later troubleshooting reliable.',
      question: 'Why is a lit link on the wrong labeled port still a fault?',
      answer: 'It violates the documented circuit and can cause future changes or diagnosis to affect the wrong service.',
    },
    hints: {
      prompt: 'Compare the occupied panel label with the ticket rather than relying only on link lights.',
      evidence: 'A-03 is occupied, but the required circuit is A-01.',
      action: 'Remove the incorrect panel cross-connect and repatch the documented one.',
      solution: 'Clear A-03 and connect A-01 to Gi1/0/1; keep SERVER-01 on Gi1/0/5.',
    },
  },
  'm5-change-window': {
    mode: 'boss',
    difficulty: 2,
    conceptsIntroduced: ['Safe cross-connect migration'],
    conceptsPracticed: ['Physical endpoints and link-state evidence', 'Cable removal and clean final state'],
    enabledTools: ['patch'],
    visibleObjectives: ['Migrate the documented panel circuit to its assigned path.', 'Keep SERVER-01 attached and finish with no abandoned cross-connects.'],
    impact: "The panel circuit must move without dropping SERVER-01 or leaving abandoned copper.",
    ticketDetails: ['The destination circuit is A-08 through Gi1/0/8.', 'The old A-01 and Gi1/0/1 endpoints must be empty after the change.'],
    debrief: {
      outcome: 'The service has moved to the new documented cross-connect with the old path fully retired.',
      explanation: 'A controlled migration verifies the destination path and removes obsolete cabling without disturbing the server-facing link.',
      question: 'What distinguishes a completed migration from merely adding a second cable?',
      answer: 'The new path is verified, service is preserved, and every retired endpoint is left clear.',
    },
    hints: {
      prompt: 'Identify the service-facing cable, the old cross-connect, and the target cross-connect before moving anything.',
      evidence: 'SERVER-01 already uses Gi1/0/5; only the A-01/Gi1/0/1 cross-connect is being migrated.',
      action: 'Move the panel cross-connect to the assigned destination and remove the old connection.',
      solution: 'Connect A-08 to Gi1/0/8, leave Gi1/0/5 connected to SERVER-01, and clear A-01 and Gi1/0/1.',
    },
  },
  'm6-fiber-first': {
    mode: 'guided',
    difficulty: 1,
    conceptsIntroduced: ['OM4 fiber media and LC endpoints'],
    conceptsPracticed: ['Physical endpoints and link-state evidence'],
    deviceUnlocks: ['Fiber tray', 'SFP switch', 'OM4 fiber patch cord'],
    enabledTools: ['patch'],
    visibleObjectives: ['Build the first fiber tray uplink.', 'Confirm the selected SFP path lights without using the disabled cage.'],
    ticketDetails: ['Patch F-01 to Te1/0/1 with OM4 fiber.', 'Te1/0/3 is administratively down.'],
    debrief: {
      outcome: 'The F-01 circuit is online through a compatible OM4/LC SFP path.',
      explanation: 'Fiber endpoints require matching optical media and connectors; copper cannot establish an optical link.',
      question: 'Why can a correctly labeled copper cord not bring up an LC SFP circuit?',
      answer: 'The physical medium and connector are incompatible with the optical ports.',
    },
    hints: {
      prompt: 'Inspect the connector and media expected by the tray and SFP cage.',
      evidence: 'Both F-01 and Te1/0/1 are fiber endpoints, while Te1/0/3 is disabled.',
      action: 'Use an OM4 cord between the enabled matching endpoints.',
      solution: 'Patch F-01 directly to Te1/0/1 with OM4 fiber.',
    },
  },
  'm7-wrong-media': {
    mode: 'practice',
    difficulty: 2,
    conceptsIntroduced: [],
    conceptsPracticed: ['OM4 fiber media and LC endpoints', 'Media compatibility diagnosis'],
    enabledTools: ['patch'],
    visibleObjectives: ['Repair the incompatible tray uplink.', 'Bring the fiber-attached server online with compatible media.'],
    ticketDetails: ['The existing F-02 circuit uses copper on fiber ports.', 'SERVER-09 has a fiber NIC.'],
    debrief: {
      outcome: 'Both the tray uplink and SERVER-09 use compatible OM4 paths.',
      explanation: 'Port labels alone do not guarantee compatibility; media and connector types must match every endpoint.',
      question: 'What evidence points to wrong media rather than an IP or VLAN fault?',
      answer: 'The physical ports are optical while the installed cord is copper, so no valid physical link can form.',
    },
    hints: {
      prompt: 'Compare each installed cable type with the endpoint connector symbols.',
      evidence: 'F-02 and Te1/0/2 expect fiber, but their current cord is Cat6.',
      action: 'Remove incompatible copper and use OM4 for both optical circuits.',
      solution: 'Patch F-02 to Te1/0/2 and SERVER-09 nic-f to Te1/0/4 with OM4 fiber.',
    },
  },
  'm9-power-up': {
    mode: 'boss',
    difficulty: 3,
    conceptsIntroduced: ['Power as a prerequisite for data links'],
    conceptsPracticed: ['Physical endpoints and link-state evidence', 'Safe cross-connect migration'],
    deviceUnlocks: ['PDU', 'C13 power cord'],
    enabledTools: ['power', 'patch'],
    visibleObjectives: ['Restore power to the switch and server.', 'Rebuild and verify the documented data path.'],
    impact: "Active gear stays dark until power returns, so the data path cannot light.",
    ticketDetails: ['Power ToR-SW-A and SERVER-01 from PDU-A.', 'The data circuit uses A-01, Gi1/0/1, Gi1/0/5, and eth0.'],
    debrief: {
      outcome: 'The active devices are powered and SERVER-01 has a working data path.',
      explanation: 'Correct data cabling cannot produce link state while either active endpoint lacks power; power and data are independent paths.',
      question: 'If a known-good data cable stays dark at both ends, what prerequisite should you inspect?',
      answer: 'Confirm that both active devices have valid PDU-to-PSU power connections.',
    },
    hints: {
      prompt: 'Separate the incident into power-path and data-path checks.',
      evidence: 'The switch and server PSUs are unpowered, so their data ports cannot light.',
      action: 'Power both devices first, then patch the documented copper circuit.',
      solution: 'Connect both PSUs to PDU outlets, A-01 to Gi1/0/1, and Gi1/0/5 to SERVER-01 eth0.',
    },
  },
  'm4-admin-down': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['Administrative-down link symptoms'],
    conceptsPracticed: ['Physical endpoints and link-state evidence', 'Cable removal and clean final state'],
    enabledTools: ['patch'],
    visibleObjectives: ['Recognize the disabled-port symptom.', 'Restore the panel circuit on a known-good spare path.'],
    ticketDetails: ['Gi1/0/4 is administratively down.', 'Gi1/0/6 is the approved spare.'],
    debrief: {
      outcome: 'The panel circuit is restored through an enabled spare switchport.',
      explanation: 'A correctly patched administratively disabled port remains dark; moving to an enabled approved port isolates that cause.',
      question: 'How can an admin-down port resemble a cabling failure?',
      answer: 'Both produce a dark link even when the cable and connectors are otherwise correct.',
    },
    hints: {
      prompt: 'Inspect port state as well as cable placement.',
      evidence: 'Gi1/0/4 is administratively down and Gi1/0/6 is available and enabled.',
      action: 'Move the panel-side connection to the approved enabled port and clear the disabled one.',
      solution: 'Connect A-04 to Gi1/0/6, clear Gi1/0/4, and keep SERVER-01 on Gi1/0/5.',
    },
  },
  'm23-no-shutdown': {
    mode: 'practice',
    difficulty: 2,
    conceptsIntroduced: ['Administrative interface recovery'],
    conceptsPracticed: ['Administrative-down link symptoms', 'Physical endpoints and link-state evidence'],
    enabledTools: ['switchport'],
    visibleObjectives: ['Restore the documented cross-connect without repatching it.', 'Keep the existing server-facing connection online.'],
    ticketDetails: ['The A-04 to Gi1/0/4 cable is already correct.', 'Enable Gi1/0/4; leave the server-facing link on Gi1/0/5 unchanged.'],
    debrief: {
      outcome: 'The documented Gi1/0/4 circuit is restored in place.',
      explanation: 'Re-enabling the intended interface fixes the root cause and avoids an undocumented spare-port workaround.',
      question: 'When should no-shutdown be preferred over moving a cable?',
      answer: 'When documentation and cabling are correct and the intended interface is simply administratively disabled.',
    },
    hints: {
      prompt: 'Decide whether the physical path or the interface state conflicts with the ticket.',
      evidence: 'The cable already lands on A-04 and Gi1/0/4, but Gi1/0/4 reports admin down.',
      action: 'Use the switchport control to enable Gi1/0/4.',
      solution: 'Select Gi1/0/4 and toggle its administrative state to up; do not move either cable.',
    },
  },
  'm28-fiber-no-shutdown': {
    mode: 'boss',
    difficulty: 3,
    conceptsIntroduced: [],
    conceptsPracticed: ['Administrative-down link symptoms', 'Administrative interface recovery', 'OM4 fiber media and LC endpoints'],
    enabledTools: ['switchport'],
    visibleObjectives: ['Recover the documented fiber circuit in place.', 'Leave the unauthorized spare fiber endpoints unused.'],
    impact: "The documented optical path stays dark despite a correct-looking patch.",
    ticketDetails: ['F-03 is correctly patched to Te1/0/3.', 'The Te1/0/3 SFP cage is administratively down.'],
    debrief: {
      outcome: 'The intended F-03 fiber path is lit without an undocumented repatch.',
      explanation: 'Administrative state affects copper and fiber alike; preserving the documented strand while enabling its SFP repairs the cause.',
      question: 'What prior diagnosis transfers unchanged from a dark copper port to a dark SFP?',
      answer: 'Check whether the interface is administratively disabled before replacing or moving the physical path.',
    },
    hints: {
      prompt: 'Do not assume a dark fiber strand is damaged; compare cabling with interface state.',
      evidence: 'F-03 and Te1/0/3 are correctly joined, but Te1/0/3 is admin down.',
      action: 'Enable the intended SFP and leave the spare pair clear.',
      solution: 'Toggle Te1/0/3 to admin up and leave F-04 and Te1/0/4 empty.',
    },
  },
  'm10-console-ip': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['Out-of-band console access and management addressing'],
    conceptsPracticed: ['Media and connector selection'],
    deviceUnlocks: ['Console server', 'Rollover cable', 'IPv4 editor'],
    enabledTools: ['console', 'ip'],
    visibleObjectives: ['Establish an out-of-band session to the switch.', 'Assign the documented management address and gateway.'],
    ticketDetails: ['Use Console TTY1 to reach the ToR console.', 'Configure 10.10.10.2/24 with gateway 10.10.10.1.'],
    debrief: {
      outcome: 'The switch is reachable through a console path and has valid management addressing.',
      explanation: 'Console access does not depend on production IP connectivity, so it provides a recovery path for configuring the management network.',
      question: 'Why is console access useful before the management IP works?',
      answer: 'It is an out-of-band serial path and therefore does not require the switch network interface to be reachable.',
    },
    hints: {
      prompt: 'Treat console connectivity and management addressing as two separate layers.',
      evidence: 'TTY1 and the switch CON port require a rollover cable; Gi1/0/1 accepts the management IP.',
      action: 'Connect the console endpoints, then enter the ticketed IPv4 values.',
      solution: 'Connect TTY1 to ToR CON and set Gi1/0/1 to 10.10.10.2/24, gateway 10.10.10.1.',
    },
  },
  'm11-subnet-ping': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['Same-subnet IPv4 reachability'],
    conceptsPracticed: ['Physical endpoints and link-state evidence', 'IPv4 interface addressing'],
    deviceUnlocks: ['Ping diagnostic'],
    enabledTools: ['patch', 'ip', 'ping'],
    visibleObjectives: ['Bring SERVER-01 onto the firewall LAN.', 'Address the server in the local /24 and prove reachability.'],
    ticketDetails: ['SERVER-01 uses 10.10.10.10/24.', 'FW-EDGE LAN is 10.10.10.1/24.'],
    debrief: {
      outcome: 'SERVER-01 can ping the firewall on their shared LAN subnet.',
      explanation: 'Hosts with matching /24 network membership and a working Layer-2 path can exchange local traffic directly.',
      question: 'What three facts support a successful same-subnet ping?',
      answer: 'Working links, compatible VLAN/Layer-2 placement, and addresses whose prefixes identify the same network.',
    },
    hints: {
      prompt: 'Check the link, then compare the server network and firewall LAN network.',
      evidence: 'The firewall is 10.10.10.1/24 and the server belongs on Gi1/0/5 in VLAN 10.',
      action: 'Patch the server, assign its address in the same /24, and run ping.',
      solution: 'Connect SERVER-01 eth0 to Gi1/0/5, set 10.10.10.10/24, then ping FW-EDGE.',
    },
  },
  'm19-broken-address': {
    mode: 'challenge',
    difficulty: 2,
    conceptsIntroduced: [],
    conceptsPracticed: ['Same-subnet IPv4 reachability', 'IPv4 interface addressing', 'Ping-based fault isolation'],
    enabledTools: ['ip', 'ping'],
    visibleObjectives: ['Diagnose why a healthy local link cannot reach the firewall.', 'Repair only the server addressing fault and verify service.'],
    impact: "Local ping to the firewall fails even though copper and power look healthy.",
    ticketDetails: [
      'The physical path is already working; only host addressing is wrong.',
      'Set SERVER-01 eth0 to 10.10.10.10/24 with gateway 10.10.10.1.',
    ],
    debrief: {
      outcome: 'Correct server addressing restores local reachability without disturbing cabling.',
      explanation: 'The original 10.10.99.10/24 address placed the server outside the firewall LAN network despite a healthy physical link.',
      question: 'What does a lit link but failed local ping suggest you inspect next?',
      answer: 'Inspect Layer-2 placement and both endpoints’ IP addresses and prefixes.',
    },
    hints: {
      prompt: 'Compare network portions rather than changing the known-good cable.',
      evidence: 'SERVER-01 is in 10.10.99.0/24 while FW-EDGE LAN is in 10.10.10.0/24.',
      action: 'Correct the server address to 10.10.10.10/24 on the firewall LAN and retest.',
      solution: 'Set eth0 to 10.10.10.10/24 with gateway 10.10.10.1, then ping FW-EDGE.',
    },
  },
  'm20-mask-trap': {
    mode: 'challenge',
    difficulty: 3,
    conceptsIntroduced: ['Prefix length determines network membership'],
    conceptsPracticed: ['Same-subnet IPv4 reachability', 'Ping-based fault isolation'],
    enabledTools: ['ip', 'ping'],
    visibleObjectives: ['Find the addressing detail that disagrees with the local network.', 'Restore and verify firewall reachability without repatching.'],
    impact: "Familiar-looking addressing still cannot reach the firewall on the LAN.",
    ticketDetails: [
      'The host address text looks familiar, but same-subnet reachability still fails.',
      'Keep 10.10.10.10 and set the prefix to /24 with gateway 10.10.10.1.',
    ],
    debrief: {
      outcome: 'SERVER-01 again interprets the LAN with the correct subnet boundary and reaches the firewall.',
      explanation: 'An IP address and prefix are a pair; the prefix determines which bits identify the network and which destinations are considered local.',
      question: 'Why is checking only the dotted-decimal host address insufficient?',
      answer: 'The prefix length changes network membership and forwarding decisions even when the host address text is unchanged.',
    },
    hints: {
      prompt: 'The address looks familiar; inspect the other half of the IPv4 configuration.',
      evidence: 'SERVER-01 is 10.10.10.10/16 while FW-EDGE LAN is 10.10.10.1/24.',
      action: 'Change only the server prefix length to /24, then use ping as evidence.',
      solution: 'Set eth0 to 10.10.10.10/24 with gateway 10.10.10.1, then ping FW-EDGE.',
    },
  },
  'm29-spare-pdu': {
    mode: 'boss',
    difficulty: 3,
    conceptsIntroduced: [],
    conceptsPracticed: ['Power as a prerequisite for data links', 'Same-subnet IPv4 reachability', 'Ping-based fault isolation'],
    enabledTools: ['power', 'ping'],
    visibleObjectives: ['Restore firewall and SERVER-07 power on the reserved outlets.', 'Prove the staged LAN service works after power recovery.'],
    impact: "Firewall and SERVER-07 stay dark after outlet reassignment until spare power is restored.",
    ticketDetails: ['OUT5 is reserved for FW-EDGE and OUT6 for SERVER-07.', 'OUT1 through OUT4 support other staged equipment.'],
    debrief: {
      outcome: 'The firewall and SERVER-07 are powered from the spare outlets and local service is verified.',
      explanation: 'Restoring the specified power paths allows the already staged data and IP configuration to operate; ping confirms more than PSU state alone.',
      question: 'Why should service verification continue after device power indicators return?',
      answer: 'Power is only a prerequisite; an end-to-end probe confirms the data path and addressing also function.',
    },
    hints: {
      prompt: 'Identify which devices are dark before changing any staged data cable.',
      evidence: 'FW-EDGE and SERVER-07 have no PSU connection; the ticket reserves OUT5 and OUT6.',
      action: 'Connect the two specified power paths, then test local reachability.',
      solution: 'Connect FW PSU to OUT5 and SERVER-07 PSU to OUT6, then ping FW-EDGE from SERVER-07.',
    },
  },
  'm12-firewall-acl': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['ACL permit rules and implicit deny'],
    conceptsPracticed: ['Same-subnet IPv4 reachability', 'Ping-based fault isolation'],
    deviceUnlocks: ['Firewall ACL editor'],
    enabledTools: ['acl', 'ping'],
    visibleObjectives: ['Allow the approved LAN flow through policy.', 'Verify that SERVER-01 can reach FW-EDGE.'],
    ticketDetails: ['The approved source and destination are both 10.10.10.0/24.', 'A deny currently blocks the flow.'],
    debrief: {
      outcome: 'The approved LAN traffic passes the firewall policy and ping succeeds.',
      explanation: 'A matching permit must authorize the traffic before a deny or implicit deny; healthy links and addresses do not bypass policy.',
      question: 'Why can ping fail when physical and IP checks are both correct?',
      answer: 'A firewall rule can deny the packet based on its source and destination.',
    },
    hints: {
      prompt: 'After confirming topology and addressing, inspect the policy decision for the probe.',
      evidence: 'An enabled deny matches traffic within 10.10.10.0/24.',
      action: 'Add an enabled permit for the approved LAN source and destination, then retest.',
      solution: 'Permit 10.10.10.0/24 to 10.10.10.0/24 and ping FW-EDGE from SERVER-01.',
    },
  },
  'm18-deny-host': {
    mode: 'boss',
    difficulty: 3,
    conceptsIntroduced: ['First-match ACL order and host-specific /32 rules'],
    conceptsPracticed: [
      'ACL permit rules and implicit deny',
      'Same-subnet IPv4 reachability',
      'Ping-based fault isolation',
    ],
    enabledTools: ['acl', 'ping'],
    visibleObjectives: ['Block only the unauthorized server from the WAN.', 'Preserve approved WAN reachability for the other server.'],
    impact: "One unauthorized host must lose WAN access while approved service continues.",
    ticketDetails: [
      'One LAN host must lose WAN access while the approved server keeps it.',
      'Deny 10.10.10.20/32 to 203.0.113.0/30 above the broad permit.',
    ],
    debrief: {
      outcome: 'SERVER-07 is blocked while SERVER-01 retains WAN access.',
      explanation: 'A /32 identifies one host, and placing its deny before the broad permit makes first-match processing selective.',
      question: 'Why must the host deny appear above the broad permit?',
      answer: 'ACL evaluation stops at the first match; the broad permit would otherwise accept the host before the deny is considered.',
    },
    hints: {
      prompt: 'Design a rule that distinguishes one source without changing the permitted destination service.',
      evidence: 'The existing any-source permit matches 10.10.10.20 before a later deny could act.',
      action: 'Place a deny for 10.10.10.20/32 to 203.0.113.0/30 ahead of the broad permit and test both outcomes.',
      solution: 'Deny 10.10.10.20/32 to 203.0.113.0/30 before the permit; verify SERVER-07 fails and SERVER-01 succeeds.',
    },
  },
  'm13-access-vlan': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['Access-port VLAN assignment'],
    conceptsPracticed: ['Physical endpoints and link-state evidence'],
    deviceUnlocks: ['Switchport VLAN controls'],
    enabledTools: ['switchport', 'patch'],
    visibleObjectives: ['Place the assigned switchport in SERVER-07’s tenant VLAN.', 'Connect the server and confirm its access link.'],
    ticketDetails: ['SERVER-07 expects VLAN 20 on Gi1/0/6.', 'Change the switchport, not the server assignment.'],
    debrief: {
      outcome: 'SERVER-07 is linked through an access port assigned to VLAN 20.',
      explanation: 'An access port carries one untagged VLAN; its VLAN assignment must agree with the endpoint’s intended tenant segment.',
      question: 'What switch setting places an untagged server into a tenant VLAN?',
      answer: 'Set the connected switchport to access mode for that VLAN ID.',
    },
    hints: {
      prompt: 'Compare the server’s expected segment with the assigned switchport VLAN.',
      evidence: 'Gi1/0/6 is VLAN 10 while SERVER-07 belongs to VLAN 20.',
      action: 'Change the access VLAN before completing the copper link.',
      solution: 'Set Gi1/0/6 to access VLAN 20 and patch it to SERVER-07 eth0.',
    },
  },
  'm3-vlan-trap': {
    mode: 'practice',
    difficulty: 2,
    conceptsIntroduced: [],
    conceptsPracticed: ['Access-port VLAN assignment', 'VLAN mismatch diagnosis', 'Cable removal and clean final state'],
    enabledTools: ['patch'],
    visibleObjectives: ['Move SERVER-07 onto a port in its assigned tenant.', 'Clear the incorrect access port when service returns.'],
    ticketDetails: [
      'SERVER-07 belongs to VLAN 20; the currently attached access port does not.',
      'Use Gi1/0/7 for SERVER-07 eth0 and leave Gi1/0/2 empty.',
    ],
    debrief: {
      outcome: 'SERVER-07 uses the VLAN 20 access path and the incorrect VLAN 10 port is clear.',
      explanation: 'A healthy copper cable does not fix a VLAN mismatch; endpoint and access-port segmentation must agree.',
      question: 'What evidence separates a VLAN mismatch from a bad cable?',
      answer: 'The physical link can be valid while the server’s expected VLAN differs from the switchport assignment.',
    },
    hints: {
      prompt: 'Look beyond cable condition and compare logical port assignments.',
      evidence: 'Gi1/0/2 is VLAN 10, while SERVER-07 requires VLAN 20 and Gi1/0/7 provides it.',
      action: 'Move the server cable to Gi1/0/7 and clear Gi1/0/2.',
      solution: 'Connect SERVER-07 eth0 to Gi1/0/7 and leave Gi1/0/2 empty.',
    },
  },
  'm14-vlan-isolation': {
    mode: 'challenge',
    difficulty: 3,
    conceptsIntroduced: ['VLANs as Layer-2 isolation boundaries'],
    conceptsPracticed: ['Access-port VLAN assignment', 'Same-subnet IPv4 reachability', 'Negative probe evidence'],
    enabledTools: ['patch', 'ip', 'ping'],
    visibleObjectives: ['Bring both tenant servers online in their assigned segments.', 'Prove that the tenant boundary blocks direct communication.'],
    impact: "Both tenants must stay linked while cross-tenant traffic remains blocked.",
    ticketDetails: [
      'Both servers must stay linked while cross-tenant ping fails.',
      'SERVER-01: 10.10.10.10/24 on VLAN 10 (Gi1/0/5); SERVER-07: 10.10.10.20/24 on VLAN 20 (Gi1/0/7).',
    ],
    debrief: {
      outcome: 'Both server links are healthy while the cross-tenant probe remains blocked.',
      explanation: 'Separate access VLANs create distinct Layer-2 broadcast domains, so a switch does not bridge traffic directly between them.',
      question: 'Why can a failed ping be the required successful outcome here?',
      answer: 'The failure is evidence that VLAN isolation is enforcing the intended tenant boundary.',
    },
    hints: {
      prompt: 'Judge physical health and policy isolation as separate outcomes.',
      evidence: 'Gi1/0/5 is VLAN 10 and Gi1/0/7 is VLAN 20; direct switching should not cross that boundary.',
      action: 'Patch SERVER-01 to Gi1/0/5 and SERVER-07 to Gi1/0/7, set 10.10.10.10/24 and 10.10.10.20/24, then confirm the negative probe.',
      solution: 'Link SERVER-01 on Gi1/0/5 at 10.10.10.10/24 and SERVER-07 on Gi1/0/7 at 10.10.10.20/24; ping between them must fail.',
    },
  },
  'm8-dual-servers': {
    mode: 'boss',
    difficulty: 3,
    conceptsIntroduced: [],
    conceptsPracticed: ['Access-port VLAN assignment', 'VLANs as Layer-2 isolation boundaries', 'Physical endpoints and link-state evidence', 'Clean rack documentation'],
    enabledTools: ['patch'],
    visibleObjectives: ['Bring both tenant servers online simultaneously.', 'Use the documented panel circuits and matching VLAN access paths.'],
    impact: "Both tenant servers must come online cleanly without crossing documented paths.",
    ticketDetails: ['A-01 documents SERVER-01 in VLAN 10.', 'A-02 documents SERVER-07 in VLAN 20.'],
    debrief: {
      outcome: 'Both tenant servers have clean, simultaneous access links on their assigned VLAN paths.',
      explanation: 'The deployment combines accurate panel documentation, compatible physical links, and VLAN-aligned switchports for multiple endpoints.',
      question: 'What should be checked independently for each server in a multi-tenant bring-up?',
      answer: 'Its documented panel path, server-facing port, link state, and assigned access VLAN.',
    },
    hints: {
      prompt: 'Trace each tenant as a separate documented circuit before adding cables.',
      evidence: 'SERVER-01 uses Gi1/0/5 in VLAN 10; SERVER-07 uses Gi1/0/7 in VLAN 20.',
      action: 'Build both panel and server sides without crossing tenant paths.',
      solution: 'Connect A-01–Gi1/0/1 and Gi1/0/5–SERVER-01; connect A-02–Gi1/0/3 and Gi1/0/7–SERVER-07.',
    },
  },
  'm15-default-gateway': {
    mode: 'guided',
    difficulty: 3,
    conceptsIntroduced: ['Default gateway for off-subnet forwarding'],
    conceptsPracticed: ['Same-subnet IPv4 reachability', 'ACL permit rules and implicit deny', 'Ping-based verification'],
    enabledTools: ['patch', 'ip', 'acl', 'ping'],
    visibleObjectives: ['Connect and address SERVER-01 on the firewall LAN.', 'Authorize and verify reachability to the ISP network.'],
    ticketDetails: ['The local gateway is FW-EDGE LAN at 10.10.10.1.', 'The approved destination is 203.0.113.0/30.'],
    debrief: {
      outcome: 'SERVER-01 reaches the off-subnet ISP peer through FW-EDGE.',
      explanation: 'The host sends nonlocal traffic to its default gateway, which forwards it only when links and firewall policy also permit the path.',
      question: 'When does a host send traffic to its default gateway?',
      answer: 'When the destination is outside the local network determined by the host address and prefix.',
    },
    hints: {
      prompt: 'Trace the path from host to local router, then through policy to the remote subnet.',
      evidence: 'SERVER-01 needs a LAN address and the firewall LAN address as its gateway; WAN policy starts denied.',
      action: 'Complete the LAN links, configure the host gateway, authorize the destination, and probe it.',
      solution: 'Use 10.10.10.10/24 gateway 10.10.10.1, permit LAN to 203.0.113.0/30, and ping ISP-PEER.',
    },
  },
  'm24-wrong-gateway': {
    mode: 'challenge',
    difficulty: 2,
    conceptsIntroduced: [],
    conceptsPracticed: [
      'Default gateway for off-subnet forwarding',
      'IPv4 interface addressing',
      'Ping-based fault isolation',
      'Prefix length determines network membership',
    ],
    enabledTools: ['ip', 'ping'],
    visibleObjectives: ['Diagnose why local configuration cannot reach the WAN.', 'Repair only the incorrect forwarding setting and verify service.'],
    impact: "LAN fabric works, but every off-subnet attempt toward the WAN fails.",
    ticketDetails: [
      'Address, prefix, links, and firewall policy are already valid; only off-subnet forwarding fails.',
      'Keep 10.10.10.10/24 and set the default gateway to 10.10.10.1.',
    ],
    debrief: {
      outcome: 'Correcting the gateway restores WAN reachability without changing healthy components.',
      explanation: 'A host can communicate locally with a wrong gateway, but off-subnet packets must be sent to a router address on its own LAN.',
      question: 'Why might local traffic work while every remote destination fails?',
      answer: 'Local traffic does not use the default gateway, while remote traffic depends on a correct reachable gateway.',
    },
    hints: {
      prompt: 'Focus on the setting used only for off-subnet destinations.',
      evidence: 'SERVER-01 is in 10.10.10.0/24, but its gateway is 10.10.20.1 instead of FW-EDGE LAN.',
      action: 'Set the gateway to 10.10.10.1 and retest WAN reachability.',
      solution: 'Keep 10.10.10.10/24, change the gateway to 10.10.10.1, and ping ISP-PEER.',
    },
  },
  'm16-trunk-uplink': {
    mode: 'guided',
    difficulty: 2,
    conceptsIntroduced: ['802.1Q trunk uplinks'],
    conceptsPracticed: ['Access-port VLAN assignment', 'Physical endpoints and link-state evidence'],
    deviceUnlocks: ['Switchport trunk control'],
    enabledTools: ['switchport', 'patch'],
    visibleObjectives: ['Prepare the assigned uplink to carry multiple VLANs.', 'Connect and verify the firewall uplink.'],
    ticketDetails: ['Gi1/0/8 is the assigned trunk.', 'The handoff terminates on FW-EDGE LAN0.'],
    debrief: {
      outcome: 'The firewall uplink is connected through a switchport operating as a trunk.',
      explanation: 'Unlike an access port’s single VLAN, a trunk is designed to carry traffic for multiple VLANs over one uplink.',
      question: 'When is trunk mode appropriate instead of access mode?',
      answer: 'On an inter-device uplink that must carry more than one VLAN rather than one untagged endpoint segment.',
    },
    hints: {
      prompt: 'Consider whether the firewall handoff serves one endpoint VLAN or an uplink role.',
      evidence: 'Gi1/0/8 is assigned as the multi-VLAN uplink but is not yet in trunk mode.',
      action: 'Set the uplink mode before patching it to the firewall.',
      solution: 'Set Gi1/0/8 to trunk and connect it to FW-EDGE LAN0.',
    },
  },
  'm21-inter-vlan': {
    mode: 'boss',
    difficulty: 4,
    conceptsIntroduced: ['Layer-3 routing between VLANs'],
    conceptsPracticed: [
      'Access-port VLAN assignment',
      'VLANs as Layer-2 isolation boundaries',
      'Default gateway for off-subnet forwarding',
      'Same-subnet IPv4 reachability',
      '802.1Q trunk uplinks',
    ],
    enabledTools: ['patch', 'ip', 'ping'],
    visibleObjectives: ['Bring both tenant networks to their firewall interfaces.', 'Configure each server for its local gateway and prove routed service.'],
    impact: "Separate tenant VLANs cannot reach each other until a Layer-3 path exists.",
    ticketDetails: [
      'Each tenant needs a firewall interface on its own LAN; trunks alone do not route.',
      'SERVER-01: 10.10.10.10/24 gw 10.10.10.1 on VLAN 10; SERVER-07: 10.10.20.10/24 gw 10.10.20.1 on VLAN 20.',
      'Patch VLAN 10 through LAN0/Gi1/0/2 and VLAN 20 through LAN20/Gi1/0/8.',
    ],
    debrief: {
      outcome: 'SERVER-01 and SERVER-07 communicate through the firewall across their VLAN boundary.',
      explanation: 'Each server forwards off-subnet traffic to a firewall interface in its own VLAN; the Layer-3 device routes between the two connected networks.',
      question: 'Why can the servers communicate now when VLAN isolation previously blocked them?',
      answer: 'A Layer-3 firewall has an interface in each network and routes traffic between them instead of relying on direct Layer-2 switching.',
    },
    hints: {
      prompt: 'Trace each server to a gateway in its own VLAN before considering the end-to-end probe.',
      evidence: 'The firewall provides separate LAN0 and LAN20 interfaces for 10.10.10.0/24 and 10.10.20.0/24.',
      action: 'Complete both server and firewall links, set each host gateway to its VLAN .1 address, then test across VLANs.',
      solution: 'Patch VLAN 10 through LAN0/Gi1/0/2 and VLAN 20 through LAN20/Gi1/0/8; address both servers with their .1 gateways.',
    },
  },
  'm17-static-nat': {
    mode: 'guided',
    difficulty: 3,
    conceptsIntroduced: ['One-to-one static NAT publication'],
    conceptsPracticed: ['ACL permit rules and implicit deny', 'Ping-based verification'],
    deviceUnlocks: ['Static NAT editor'],
    enabledTools: ['nat', 'acl', 'ping'],
    visibleObjectives: ['Publish the internal server at its assigned public address.', 'Authorize inbound traffic and verify the external service path.'],
    ticketDetails: ['Map inside 10.10.10.10 to outside 203.0.113.10.', 'The WAN subnet needs permission toward the LAN subnet.'],
    debrief: {
      outcome: 'The internal server is published through its stable public NAT mapping.',
      explanation: 'Static NAT translates a fixed outside address to one inside host, while policy separately decides whether inbound traffic is allowed.',
      question: 'Why are both a NAT mapping and an ACL permit needed?',
      answer: 'NAT determines address translation; the ACL independently authorizes the flow.',
    },
    hints: {
      prompt: 'Separate address publication from the firewall’s allow-or-deny decision.',
      evidence: 'No static mapping exists and inbound WAN-to-LAN traffic is denied.',
      action: 'Create the one-to-one mapping, permit the approved source, and probe from outside.',
      solution: 'Map 10.10.10.10 to 203.0.113.10, permit 203.0.113.0/30 to 10.10.10.0/24, then ping from ISP-PEER.',
    },
  },
  'm31-pat-overload': {
    mode: 'boss',
    difficulty: 4,
    conceptsIntroduced: ['Many-to-one PAT overload'],
    conceptsPracticed: [
      'One-to-one static NAT publication',
      'Default gateway for off-subnet forwarding',
      'ACL permit rules and implicit deny',
      'Address translation',
    ],
    enabledTools: ['pat', 'ping'],
    visibleObjectives: ['Restore outbound translation for the private LAN.', 'Verify that a LAN host can use the shared WAN address.'],
    impact: "Private LAN hosts still cannot leave for the WAN despite healthy route and ACL.",
    ticketDetails: [
      'Private LAN hosts need shared egress through the firewall outside address.',
      'Overload 10.10.10.0/24 to FW-EDGE WAN 203.0.113.1.',
    ],
    debrief: {
      outcome: 'Private LAN traffic reaches the ISP through the firewall’s shared outside address.',
      explanation: 'PAT translates many inside sessions to one outside IP by distinguishing flows, allowing RFC1918 hosts to share WAN egress.',
      question: 'How does PAT differ from the earlier static NAT mapping?',
      answer: 'PAT lets many inside hosts share one outside address, while static NAT reserves a stable one-to-one address mapping.',
    },
    hints: {
      prompt: 'The route and policy work; inspect what the WAN requires from private source addresses.',
      evidence: 'FW-EDGE requires outbound translation, but no overload rule covers 10.10.10.0/24 to 203.0.113.1.',
      action: 'Apply PAT from 10.10.10.0/24 to 203.0.113.1, then test egress.',
      solution: 'Configure PAT 10.10.10.0/24 to 203.0.113.1 and ping ISP-PEER from SERVER-01.',
    },
  },
  'm22-static-route': {
    mode: 'guided',
    difficulty: 3,
    conceptsIntroduced: ['Static routes to remote prefixes'],
    conceptsPracticed: [
      'Default gateway for off-subnet forwarding',
      'ACL permit rules and implicit deny',
      'Ping-based verification',
      'Layer-3 routing between VLANs',
    ],
    deviceUnlocks: ['Route table editor', 'Branch site'],
    enabledTools: ['route', 'acl', 'ping'],
    visibleObjectives: ['Teach FW-EDGE how to reach the branch network.', 'Authorize and verify the LAN-to-branch service path.'],
    ticketDetails: ['BRANCH uses 198.51.100.0/24.', 'ISP-PEER at 203.0.113.2 is the next hop.'],
    debrief: {
      outcome: 'The firewall forwards LAN traffic toward the remote branch prefix through ISP-PEER.',
      explanation: 'A static route associates a destination prefix with a reachable next hop; policy must also permit the forwarded flow.',
      question: 'What two pieces of information define this static route?',
      answer: 'The remote destination prefix and the next-hop address used to reach it.',
    },
    hints: {
      prompt: 'Identify which device lacks knowledge of the remote network and which adjacent peer can forward toward it.',
      evidence: 'FW-EDGE has a connected WAN peer but no route for 198.51.100.0/24.',
      action: 'Add the branch route, permit the flow, and verify from the LAN.',
      solution: 'Route 198.51.100.0/24 via 203.0.113.2, permit LAN to branch, and ping BRANCH-01.',
    },
  },
  'm25-host-route': {
    mode: 'challenge',
    difficulty: 4,
    conceptsIntroduced: ['Longest-prefix route selection'],
    conceptsPracticed: ['Static routes to remote prefixes', 'Ping-based fault isolation'],
    enabledTools: ['route', 'ping'],
    visibleObjectives: ['Identify why one branch host ignores the working summary path.', 'Restore that destination without changing the WAN or ACL.'],
    impact: "BRANCH is unreachable for one destination while broader routing looks intact.",
    ticketDetails: [
      'A working /24 branch summary exists, but one host still black-holes.',
      'Set 198.51.100.10/32 next hop to 203.0.113.2 (ISP-PEER).',
    ],
    debrief: {
      outcome: 'BRANCH-01 follows the corrected host route through ISP-PEER.',
      explanation: 'Routers prefer the longest matching prefix, so a /32 route controls this host even when a valid /24 route also matches.',
      question: 'Why does the /32 route win over the /24 route?',
      answer: 'The /32 is a longer, more-specific prefix and therefore is selected for that destination.',
    },
    hints: {
      prompt: 'Compare every matching route by prefix specificity, not only by whether a summary exists.',
      evidence: 'The 198.51.100.10/32 entry is more specific and points to 10.10.10.10 instead of ISP-PEER.',
      action: 'Change the 198.51.100.10/32 next hop to 203.0.113.2 and retest.',
      solution: 'Set 198.51.100.10/32 to next hop 203.0.113.2 and ping BRANCH-01.',
    },
  },
  'm30-floating-static': {
    mode: 'boss',
    difficulty: 5,
    conceptsIntroduced: ['Administrative distance and floating backup routes'],
    conceptsPracticed: [
      'Static routes to remote prefixes',
      'Longest-prefix route selection',
      'Ping-based fault isolation',
    ],
    enabledTools: ['route', 'ping'],
    visibleObjectives: ['Preserve the configured primary route while adding branch resilience.', 'Recover branch service through the valid backup path.'],
    impact: "Preferred BRANCH forwarding is withdrawn; service needs a backup path.",
    ticketDetails: [
      'The preferred primary is withdrawn by failed reachability tracking; branch service needs a backup path.',
      'Keep 198.51.100.0/24 via 10.10.10.10 at AD1; add 198.51.100.0/24 via 203.0.113.2 at AD10.',
    ],
    debrief: {
      outcome: 'The branch prefix has a retained primary route and a usable higher-distance backup.',
      explanation: 'For equal prefixes, lower administrative distance is preferred while tracked healthy; when tracking withdraws the primary, the floating static becomes eligible through its alternate next hop.',
      question: 'Why is the backup configured with a higher administrative distance?',
      answer: 'So it does not displace a healthy trusted primary route but remains available as a less-preferred alternative.',
    },
    hints: {
      prompt: 'Keep prefix specificity constant and compare route preference and next-hop viability.',
      evidence: 'The tracked-down AD1 route to 198.51.100.0/24 via 10.10.10.10 remains configured; ISP-PEER 203.0.113.2 is the valid alternate.',
      action: 'Add 198.51.100.0/24 via 203.0.113.2 with administrative distance 10.',
      solution: 'Keep the AD1 route and add 198.51.100.0/24 via 203.0.113.2 at AD10, then ping BRANCH-01.',
    },
  },
  'm26-deny-branch': {
    mode: 'practice',
    difficulty: 3,
    conceptsIntroduced: [],
    conceptsPracticed: ['First-match ACL order and host-specific /32 rules', 'Static routes to remote prefixes', 'Negative probe evidence'],
    enabledTools: ['acl', 'ping'],
    visibleObjectives: ['Block one unauthorized branch client.', 'Keep branch access working for the approved server.'],
    ticketDetails: [
      'One LAN host must lose branch access while the approved server keeps it.',
      'Deny 10.10.10.20/32 to 198.51.100.0/24 above the existing LAN-to-branch permit.',
    ],
    debrief: {
      outcome: 'SERVER-07 is denied to the routed branch while SERVER-01 remains authorized.',
      explanation: 'The earlier host-specific first-match policy pattern applies equally to a remote routed destination prefix.',
      question: 'Which parts of the earlier WAN host-deny pattern change for a branch policy?',
      answer: 'The destination prefix changes to the branch network; host specificity and rule ordering stay the same.',
    },
    hints: {
      prompt: 'Reuse the selective-deny pattern without changing the known-good route.',
      evidence: 'A broad permit for 10.10.10.0/24 to 198.51.100.0/24 currently matches SERVER-07 as well as SERVER-01.',
      action: 'Insert deny 10.10.10.20/32 to 198.51.100.0/24 before the broad branch permit and test both hosts.',
      solution: 'Deny 10.10.10.20/32 to 198.51.100.0/24 first; verify SERVER-07 fails and SERVER-01 succeeds.',
    },
  },
  'm27-branch-exception': {
    mode: 'challenge',
    difficulty: 4,
    conceptsIntroduced: ['Narrow ACL exceptions above broad denies'],
    conceptsPracticed: ['First-match ACL order and host-specific /32 rules', 'Out-of-band console access and management addressing', 'Negative probe evidence'],
    enabledTools: ['console', 'acl', 'ping'],
    visibleObjectives: ['Use the recovery path to make a least-privilege policy change.', 'Restore one approved branch flow without opening access for other hosts.'],
    impact: "BRANCH is locked down for the LAN; one approved host needs a narrow exception.",
    ticketDetails: [
      'BRANCH is locked for the LAN; only one approved host-to-host flow may return.',
      'Console in, then permit 10.10.10.10/32 to 198.51.100.10/32 above the broad deny.',
    ],
    debrief: {
      outcome: 'Only SERVER-01 can reach BRANCH-01, and the broader branch denial remains effective.',
      explanation: 'A narrowly scoped host-to-host permit placed before a broad deny creates the required exception without weakening policy for the rest of the LAN.',
      question: 'Why use /32 source and destination prefixes for this exception?',
      answer: 'They constrain the permit to exactly one source host and one destination host.',
    },
    hints: {
      prompt: 'Find the smallest rule that can precede the broad deny and satisfy the approved flow.',
      evidence: 'TTY recovery console can reach the firewall; only 10.10.10.10 to 198.51.100.10 should pass.',
      action: 'Connect out of band, add permit 10.10.10.10/32 to 198.51.100.10/32 before the deny, and test both cases.',
      solution: 'Console TTY2 to FW CON; permit 10.10.10.10/32 to 198.51.100.10/32 above the deny; SERVER-01 succeeds and SERVER-07 fails.',
    },
  },
  'm32-traceroute': {
    mode: 'boss',
    difficulty: 5,
    conceptsIntroduced: ['Traceroute as path evidence'],
    conceptsPracticed: [
      'Static routes to remote prefixes',
      'ACL permit rules and implicit deny',
      'Narrow ACL exceptions above broad denies',
      'Administrative distance and floating backup routes',
      'Many-to-one PAT overload',
    ],
    enabledTools: ['route', 'traceroute', 'ping'],
    visibleObjectives: [
      'Restore BRANCH path.',
      'Prove the hop path with traceroute.',
    ],
    impact: "BRANCH stays dark from SERVER-01 until hop evidence proves the repaired path.",
    ticketDetails: [
      'Firewall policy toward BRANCH is already open — focus on forwarding.',
      'Add route 198.51.100.0/24 via 203.0.113.2, then traceroute SERVER-01 → BRANCH-01.',
    ],
    debrief: {
      outcome: 'The end-to-end branch path completes and traceroute records each routed hop.',
      explanation:
        'With policy already open, missing forwarding still stops the path; traceroute shows how far packets travel before the break.',
      question:
        'How does traceroute narrow a layered fault more effectively than a final ping result?',
      answer:
        'It shows the last responding hop, revealing how far forwarding succeeds before the path stops.',
    },
    hints: {
      prompt:
        'Run traceroute and note the last hop that answers before BRANCH stays dark.',
      evidence:
        'LAN and WAN adjacency respond; there is no installed route for the BRANCH prefix yet.',
      action:
        'Install the BRANCH static via ISP-PEER, then rerun traceroute until the path completes.',
      solution:
        'Route 198.51.100.0/24 via 203.0.113.2, then traceroute SERVER-01 to BRANCH-01.',
    },
  },
} satisfies Record<CampaignMissionId, LearningDesign>;

export function isCampaignMissionId(id: string): id is CampaignMissionId {
  return Object.prototype.hasOwnProperty.call(LEARNING_DESIGN_BY_ID, id);
}
